### ISSUE TITLE
torch.cuda.FloatTensor is not enabled.

### ISSUE THREAD

**Issue by Miserness974** [JakeRenn/AI-Challenger-Keypoints-pytorch#5]
Hello,

I am trying to make your program work on my Mac. I have try a lot of things to solve this problem. My problem is that I got this error:

`Traceback (most recent call last):
  File "/Users/user/Downloads/pytorch_Realtime_Multi-Person_Pose_Estimation-master/web_demo.py", line 143, in <module>
    model.cuda()
  File "/Users/user/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 249, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/Users/user/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/Users/user/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 176, in _apply
    module._apply(fn)
  File "/Users/user/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 182, in _apply
    param.data = fn(param.data)
  File "/Users/user/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 249, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: torch.cuda.FloatTensor is not enabled.
[Finished in 2.7s with exit code 1]
[shell_cmd: python -u "/Users/user/Downloads/pytorch_Realtime_Multi-Person_Pose_Estimation-master/web_demo.py"]
[dir: /Users/user/Downloads/pytorch_Realtime_Multi-Person_Pose_Estimation-master]
[path: /Users/user/anaconda2/bin:/Users/user/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin]`

How can I solve it please ?

Thx,
Miserness

**Comment by c1a1o1** [comment]
How to install your nms？ @Miserness974
